
### GET matching places
GET http://localhost:3001/api/places/search?q=knihovna 

### GET place by id
GET http://localhost:3001/api/places/90

### Add review
POST http://localhost:3001/api/places/90/reviews
Content-Type: application/json

{
  "text": "This is a great place",
  "rating": 5
}

  

