### update database
GET http://localhost:3001/api/test/update-db 
 
### Get all places
GET http://localhost:3001/api/places

### Get a places by id
GET http://localhost:3001/api/places/077c74960b5b2d702ce12efac6e316fd

### GET all places
GET http://localhost:3001/api/places

### POST a new places
POST http://localhost:3001/api/places
Content-Type: application/json

{
  "name": "Location 1",
  "address": "Address 1",
  "city": "City 1",
  "state": "State 1",
  "country": "Country 1",
  "latitude": 1,
  "longitude": 1
}
### PUT a places
PUT http://localhost:3001/api/places/1
Content-Type: application/json

{
  "name": "Location 1",
  "address": "Address 1",
  "city": "City 1",
  "state": "State 1",
  "country": "Czech Republic",
  "latitude": 1,
  "longitude": 1
}

### DELETE a places
DELETE http://localhost:3001/api/places/1

### Update a places
PUT http://localhost:3001/api/places/077c74960b5b2d702ce12efac6e316fd
Content-Type: application/json

{
  "name": "Location 1",
  "address": "Address 1",
  "city": "City 1",
  "state": "State 1",
  "country": "Ethiopia",
  "latitude": 1,
  "longitude": 1
}